version: '3.8'

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend


  adminer:
    ## http://localhost:8080/?server=mysqldb&username=root&db=bezkoder_db&select=tutorials
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
  
  api:
    depends_on:
      - mysqldb
    build: ./API
    restart: unless-stopped

    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend


  ui:
    depends_on:
      - api
    build:
      context: ./UI 
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend  


volumes: 
  db:

networks:
  backend:
  frontend:


## 1. docker-compose 

# docker-compose --env-file env.txt down  

# docker-compose --env-file env.txt up -d

# docker-compose up -d --build bezkoder-api

# docker-compose stop bezkoder-api


## 2. docker 
## https://medium.com/@jmake/jupyter-dockerfiles-ee7f544f48bb

## docker exec --tty --interactive ${CONTAINER_NAME} ${TOBEEXECUTED} 
